http:
  port: 5050

apiEndpoints:
  employeeEndpoint:
    path: /employee/*
    methods: GET, POST, PUT, DELETE, OPTIONS
  authenticationEndpoint:
    path: /auth/*
    methods: GET, POST, PUT, DELETE, OPTIONS
  userEndpoint:
    path: /user/*
    methods: GET, POST, PUT, DELETE, OPTIONS
  orderEndpoint:
    path: /order/*
    methods: GET, POST, PUT, DELETE, OPTIONS
  productEndpoint:
    path: /product/*
    methods: GET, POST, PUT, DELETE, OPTIONS
  reportEndpoint:
    path: /report/*
    methods: GET, POST, PUT, DELETE, OPTIONS

serviceEndpoints:
  employeeService:
    url: http://localhost:5051
  authenticationService:
    url: http://localhost:5052
  userService:
    url: http://localhost:5053
  orderService:
    url: http://localhost:5054
  productService:
    url: http://localhost:5055
  reportService:
    url: http://localhost:5056

pipelines:
  employeePipeline:
    apiEndpoints:
      - employeeEndpoint
    policies:
      - log:
          - action:
              message: "Incoming request to /employee/*"
      - proxy:
          - action:
              serviceEndpoint: employeeService
      - jwt:
          - action:
              secretOrPublicKey: "chuongdz"
              algorithms:
                - HS256
              credentialsRequired: true
              options:
                ignoreExpiration: false
  authenticationPipeline:
    apiEndpoints:
      - authenticationEndpoint
    policies:
      - log:
          - action:
              message: "Incoming request to /auth/*"
      - proxy:
          - action:
              serviceEndpoint: authenticationService
  userPipeline:
    apiEndpoints:
      - userEndpoint
    policies:
      - log:
          - action:
              message: "Incoming request to /user/*"
      - proxy:
          - action:
              serviceEndpoint: userService
      - jwt:
          - action:
              secretOrPublicKey: "chuongdz"
              algorithms:
                - HS256
              credentialsRequired: true
              options:
                ignoreExpiration: false
  orderPipeline:
    apiEndpoints:
      - orderEndpoint
    policies:
      - log:
          - action:
              message: "Incoming request to /order/*"
      - proxy:
          - action:
              serviceEndpoint: orderService
      - jwt:
          - action:
              secretOrPublicKey: "chuongdz"
              algorithms:
                - HS256
              credentialsRequired: true
              options:
                ignoreExpiration: false
  productPipeline:
    apiEndpoints:
      - productEndpoint
    policies:
      - log:
          - action:
              message: "Incoming request to /product/*"
      - proxy:
          - action:
              serviceEndpoint: productService
      - jwt:
          - action:
              secretOrPublicKey: "chuongdz"
              algorithms:
                - HS256
              credentialsRequired: true
              options:
                ignoreExpiration: false
  reportPipeline:
    apiEndpoints:
      - reportEndpoint
    policies:
      - log:
          - action:
              message: "Incoming request to /report/*"
      - proxy:
          - action:
              serviceEndpoint: reportService
      - jwt:
          - action:
              secretOrPublicKey: "chuongdz"
              algorithms:
                - HS256
              credentialsRequired: true
              options:
                ignoreExpiration: false
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
