http:
  port: 5050

apiEndpoints:
  employeeEndpoint:
    path: /employee/*
    methods: GET, POST, PUT, DELETE

serviceEndpoints:
  employeeService:
    url: http://localhost:5051

pipelines:
  employeePipeline:
    apiEndpoints:
      - employeeEndpoint
    policies:
      - log:
          - action:
              message: "Incoming request to /employee/*"
      - proxy:
          - action:
              serviceEndpoint: employeeService 

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

